import { useState } from 'react';
import { CheckCircle2, Mail, MapPin, Send } from 'lucide-react';
import PageHero from '../components/PageHero';
import { products } from '../data/siteData';
import { submitContactMessage } from '../lib/api';

const topics = ['Product feedback', 'Partnership or integration', 'Investment', 'Media', 'Company enquiry', 'Other'];

export default function Contact() {
  const [form,setForm]=useState({name:'',email:'',topic:'Product feedback',product:'',subject:'',message:'',website:''});
  const [state,setState]=useState({loading:false,error:'',sent:false,reference:'',confirmed:false,notice:''});
  const update=(e)=>setForm((current)=>({...current,[e.target.name]:e.target.value}));
  async function submit(e){e.preventDefault();setState({loading:true,error:'',sent:false,reference:'',confirmed:false,notice:''});try{const data=await submitContactMessage(form);setForm({name:'',email:'',topic:'Product feedback',product:'',subject:'',message:'',website:''});setState({loading:false,error:'',sent:true,reference:data.reference||'',confirmed:Boolean(data.confirmationEmailSent),notice:data.notice||''});}catch(error){setState({loading:false,error:error.message||'Could not send your message.',sent:false,reference:'',confirmed:false,notice:''});}}
  return <>
    <PageHero eyebrow="Contact ENASH" title="Talk to the team behind the products." text="Use this form for product feedback, partnerships, integrations, investment conversations, media enquiries or general company matters." side={<div className="contact-direct"><Mail size={19}/><span>Direct email</span><a href="mailto:thendos@enash.co.za">thendos@enash.co.za</a></div>}/>
    <section className="section"><div className="container contact-grid"><div className="contact-info"><span className="eyebrow">Start a conversation</span><h2>Tell us what you want to discuss.</h2><p>Your message is sent directly to the ENASH company inbox. Product-specific messages can be tagged to one of the products below.</p><div className="contact-info-row"><MapPin size={19}/><div><span>Based in</span><strong>Johannesburg, Gauteng, South Africa</strong></div></div><div className="contact-info-row"><Mail size={19}/><div><span>Company email</span><strong>thendos@enash.co.za</strong></div></div></div><form className="enash-form" onSubmit={submit}>{state.sent&&<div className="form-success-inline"><CheckCircle2 size={17}/> Message received. Reference {state.reference}.</div>}{state.sent&&state.confirmed&&<div className="form-success-inline"><CheckCircle2 size={17}/> A confirmation was sent to your email.</div>}{state.notice&&<div className="form-notice">{state.notice}</div>}<div className="form-grid two"><label>Name *<input name="name" value={form.name} onChange={update} required maxLength={120}/></label><label>Email *<input name="email" type="email" value={form.email} onChange={update} required maxLength={180}/></label></div><div className="form-grid two"><label>Topic *<select name="topic" value={form.topic} onChange={update}>{topics.map((item)=><option key={item}>{item}</option>)}</select></label><label>Product<select name="product" value={form.product} onChange={update}><option value="">General / none</option>{products.map((item)=><option key={item.slug} value={item.name}>{item.name}</option>)}</select></label></div><label>Subject *<input name="subject" value={form.subject} onChange={update} required maxLength={180} placeholder="A short summary"/></label><label>Message *<textarea name="message" value={form.message} onChange={update} required minLength={10} maxLength={5000} rows={8} placeholder="Tell us a little more…"/></label><label className="honeypot" aria-hidden="true">Website<input name="website" value={form.website} onChange={update} tabIndex="-1" autoComplete="off"/></label>{state.error&&<div className="form-error">{state.error}</div>}<button className="btn btn-dark btn-lg" disabled={state.loading}>{state.loading?'Sending…':<>Send message <Send size={16}/></>}</button></form></div></section>
  </>;
}
