name: Deploy ENASH to Azure

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_04CFB12D8D314936B8698A424F7E840D }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_FA40A7E853C1471586DB12AED2DA8A4F }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_28BE5729D8E54E16B611292458B45A13 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: enash
          slot-name: Production
          package: .
